version: '3'
services:
  proxy:
    image: nginx:latest
    restart: 'always'
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  ninetail_webapp:
    image: ninetail_webapp:latest 
    expose:
      - "7000"
  ninetail_webapi:
    image: ninetail_webapi:latest 
    expose:
      - "5000"